apiVersion: v1
kind: Service
metadata:
  name: assignment2-service
spec:
  type: NodePort
  selector:
    app: assignment2
  ports:
    - protocol: TCP
      port: 3030  # Port exposed by the service
      targetPort: 3030  # Port on the container to forward traffic to
      nodePort: 30030  # NodePort to access the service from outside the cluster
